### ISSUE TITLE
Animation does not work in DotLottie Web

### ISSUE THREAD

**Issue by PrinceGupta1999** [LottieFiles/dotlottie-web#164]
## Overview

Hi, I am trying to integrate this lottie animation (that I had exported from figma), https://app.lottiefiles.com/share/352a1071-0e63-44f2-9bd8-a6b94026600d, into my react app but it does not seem to work at all (it renders a blank canvas). Both the .json and .lottie formats do not seem to work.

**Lottie .json**: https://lottie.host/c47dca0a-2580-41b8-b2e9-75a9aeeb017b/Ja2z677E9b.json
**.lottie**: https://lottie.host/70cdd9e4-7e68-4166-9769-4ea6e4412fd6/GOZKlPuo9N.lottie
**Codepen**: https://codepen.io/tayyari/pen/wvZyXRZ

This is how it's supposed to look
<img width="1098" alt="Screenshot 2024-04-05 at 8 22 33 PM" src="https://github.com/LottieFiles/dotlottie-web/assets/32774830/11dc4acd-9074-4c16-a162-773fa08d47cd">

## Consuming repo

> What repo were you working in when this issue occurred?
dotlottie-web

...

## Labels

- [] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
Thank you, @PrinceGupta1999, for reporting this issue. I believe it is related to [ThorVG](https://github.com/thorvg/thorvg), the underlying Lottie renderer engine we use in dotLottie players.

I have reported the issue to the ThorVG team and linked it here for you to track its progress.

**Comment by hermet** [comment]
Hello, unfortunately, we cannot use this resource at the moment due to the lack of support for "layer effects." We plan to support it, but it will take a few months. Perhaps, you can find an alternative method to convert this resource without relying on layer effects. For example:
- Using a blurred shadow effect images beneath the leaf shapes. 
- Replace the effect with the additional shapes with radial-gradient filling beneath the leaf shapes .

Otherwise, using a different player(engine).

**Comment by theashraf** [comment]
@PrinceGupta1999 This has been fixed in the latest dotLottie-web v0.37.0 

You can test it out on the dotLottie viewer https://lottiefiles.github.io/dotlottie-web/

<img width="400" alt="image" src="https://github.com/user-attachments/assets/30eb2669-2558-485a-9f1d-60d11a64dc97">
