### ISSUE TITLE
Can not load assets .lottie files

### ISSUE THREAD

**Issue by rjlatgithub** [LottieFiles/dotlottie-web#393]
It's a terrific component~
But I have a question. When I use dotlottie-react, I got an Unexpected error.
If I use remote file url, it works well. Like this:
`
src='https://oss.aliyuncs.com/demo/groovyWalk.lottie'
`
But if I use local file, it doesn't work. Like this:
`
src='../../assets/anims/groovyWalk.lottie'
`

I tried to convert the file to ArrayBuffer, It still failed. Like this:
`
fetch("../../assets/anims/groovyWalk.lottie")
            .then((response) => {
                if (response.ok) {
                    return response.arrayBuffer();
                }
                throw new Error("Network response was not ok.");
            })
            .then((buffer) => {
                setFileData(buffer);
            })

data={fileData}
`

So how can I use local .lottie files in dotlottie-react?

Thanks very much~

**Comment by mabernethy** [comment]
What's the error you're seeing in the browser console?

**Comment by theashraf** [comment]
@rjlatgithub This issue is not related to dotlottie-react itself but rather concerns how the src property is provided. The src is expected to be either:

- A valid relative URL pointing to your asset, or
- A full URL to the remote asset.

If you're using something like `../../assets/anims/groovyWalk.lottie`, it needs to resolve to a valid relative URL accessible by the browser, not just a directory path.

To ensure this works, you can configure your bundler to properly handle the .lottie files. For instance, if you are using `vite`, you can leverage the ?url import query to load the asset as a URL.

```js
import srcUrl from "./../assets/anims/groovyWalk.lottie?url";

...
<DotLottieReact src={srcUrl} />
...
```

**Comment by theashraf** [comment]
@rjlatgithub  feel free to reopen the issue if you're still experiencing the same problem.
